### ISSUE TITLE
Source File Not Found

### ISSUE THREAD

**Issue by pgwalsh** [stbenz/oe-ffmpeg#1]
Wasn't able to find the source listed in package.mk

Cant't get tvheadend sources  http://stbenz.de/openelec/sources/tvheadend-3.9.2709.tar.gz
404 File Not Found: http://sources.openelec.tv/mirror/tvheadend/tvheadend-3.9.2709.tar.gz

**Comment by stbenz** [comment]
Sorry, forgot to upload the source archive. Should work now.
